# Docker-compose.yml

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - mynetwork
    volumes:
      - ./mysql_data:/var/lib/mysql
    
  app:
    build: .
    ports:
      - "${APP_PORT}:3000"
    container_name: node_app
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASS}
      DB_NAME: ${MYSQL_DB}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge